stress and custom experiment
atomistic-machine-learning/schnetpack pull request #292
Opened 2021-05-26 13:05 UTC by Stefaanhess

2021-05-27 08:01 UTC, ktschuett commented on src/schnetpack/configs/model/pes.yaml
> +    loss_weight: 0.90
why?

2021-05-27 08:05 UTC, ktschuett requested changes

2021-05-27 08:05 UTC, ktschuett commented on src/schnetpack/configs/data/custom.yaml
> +datapath: ${data_dir}/custom.db  # data_dir is specified in train.yaml
i think this should be None, since this default does not make sense

2021-05-27 08:05 UTC, ktschuett commented on src/schnetpack/configs/data/custom.yaml
> +batch_size: 2
bit small?

2021-05-27 08:05 UTC, ktschuett commented on src/schnetpack/configs/experiment/custom.yaml
> +seed: 1234
set to None by default

2021-05-27 08:05 UTC, ktschuett commented on src/schnetpack/model/pes.py
> +            results = self.postprocess(inputs, results)
this should be outside `if`

2021-05-27 08:05 UTC, ktschuett commented on src/schnetpack/configs/experiment/custom.yaml
> +  - override /logger: tensorboard
perhaps just rename to pes.yaml

2021-05-28 15:08 UTC, Stefaanhess commented on src/schnetpack/configs/model/pes.yaml
> +    loss_weight: 0.90
0.05 energy + 0.9 forces + 0.05 stress

2021-05-28 15:28 UTC, ktschuett approved these changes

2021-05-28 15:35 UTC, merged