Sh jl/lammps
atomistic-machine-learning/schnetpack pull request #501
Opened 2023-03-03 15:29 UTC by Stefaanhess

**LAMMPS Interface**

- added JIT support for spk-models
- spkdeploy script to create JIT models
- C++ interface for LAMMPS
- script for patching C++ interface into lammps installation
- tutorial for installation and usage of LAMMPS interface
- example files and trained model to test lammps interface

2023-03-03 16:37 UTC, mgastegger approved these changes

2023-03-03 17:14 UTC, mgastegger approved these changes

2023-03-07 11:45 UTC, Stefaanhess commented
should be ready for merge now

2023-03-07 11:53 UTC, mgastegger requested changes
Looks good, there is just a small typo in Tensosboard in the README.md

2023-03-07 11:55 UTC, NiklasGebauer commented on README.md
> +- PyTorch Lightning 1.4.5
Versions should match setup.py (1.9)

2023-03-07 12:04 UTC, NiklasGebauer requested changes
We should update the version numbers from requirements in the readme (or maybe remove them as they change all the time?)

2023-03-07 12:29 UTC, NiklasGebauer approved these changes
Looking fine I think.

2023-03-07 12:30 UTC, mgastegger approved these changes

2023-03-07 12:37 UTC, merged